-- =============================================================================
-- musteri_metrik_gecmis — gunluk metrik anlik goruntusu (2026-08-11 audit'i, K3)
-- =============================================================================
--
-- NE ISE YARIYOR
--   Raporlama tablosundaki "Trend 14g" sparkline'inin TEK veri kaynagi
--   (frontend/hooks/useMusteriRaporlama.ts -> useMusteriTrend).
--   Her gun her musteri icin bir satir birikiyor.
--
-- !! DIKKAT — BU DOSYA MEVCUT DURUMUN BELGESIDIR, KAYNAGI DEGILDIR !!
--   Audit sirasinda tespit edildi: bu tabloyu YAZAN is repoda YOK.
--   Ne DDL, ne cron, ne Edge Function, ne trigger — hicbir sey. Buna ragmen
--   tablo her gun dolmaya devam ediyor (9/10/11 Agu -> 1200/1200/1203 satir),
--   yani Supabase projesinde surum kontrolu DISINDA bir is calisiyor
--   (buyuk ihtimalle pg_cron job'u veya zamanlanmis bir function).
--
--   Sonuc: bu is gozden gecirilemiyor, degistirilemiyor, bozulursa geri
--   alinamiyor ve kimse fark etmeden durabilir — durursa sparkline sessizce
--   donar (tıpkı 2026-08-06'daki transform olayi gibi).
--
-- YAPILMASI GEREKEN (bu dosya tek basina yeterli DEGIL)
--   1) Supabase'de yazan isi bul:
--        select * from cron.job;                       -- pg_cron kurulu ise
--        select proname, prosrc from pg_proc
--         where prosrc ilike '%musteri_metrik_gecmis%';
--   2) Bulunan job/function tanimini bu dosyanin altina EKLE, boylece kaynak
--      surum kontrolune girsin.
--   3) O zamana kadar: tablonun her gun dolup dolmadigini izle.
--
-- Asagidaki tablo tanimi CANLI SEMADAN turetildi (PostgREST ile gozlemlenen
-- kolonlar ve degerler). Tablo zaten var; bu blok yalnizca yeniden kurulum /
-- ikinci ortam icin idempotent olarak yazildi.
-- =============================================================================

create table if not exists public.musteri_metrik_gecmis (
  id                     bigint generated by default as identity primary key,
  musteri_kodu           text not null,
  snapshot_tarihi        date not null,
  net_ciro               numeric,
  siparis_sayisi         integer,
  fatura_sayisi          integer,
  acik_bakiye            numeric,
  riskli_bakiye          numeric,
  son_teslimat_tarihi    date,
  toplam_teslimat_sayisi integer not null default 0,
  risk_durumu            text,
  unique (musteri_kodu, snapshot_tarihi)
);

-- useMusteriTrend: son 14 gunu musteri_kodu listesiyle cekiyor.
create index if not exists idx_metrik_gecmis_kod_tarih
  on public.musteri_metrik_gecmis (musteri_kodu, snapshot_tarihi desc);

create index if not exists idx_metrik_gecmis_tarih
  on public.musteri_metrik_gecmis (snapshot_tarihi desc);

alter table public.musteri_metrik_gecmis enable row level security;

-- UI anon anahtarla okuyor (RAPORLAMA-SAYFASI.md:215 bu boslugu isaret ediyordu).
drop policy if exists "metrik_gecmis_read" on public.musteri_metrik_gecmis;
create policy "metrik_gecmis_read"
  on public.musteri_metrik_gecmis
  for select
  to anon, authenticated
  using (true);

-- Dogrulama — gunluk is calisiyor mu:
--   select snapshot_tarihi, count(*)
--     from public.musteri_metrik_gecmis
--    group by 1 order by 1 desc limit 14;
-- Beklenen: her gun icin ~musteri sayisi kadar satir, bosluk yok.

-- =============================================================================
-- BULUNDU (2026-08-13 audit'i) — yazan is pg_cron, n8n'de degil, repoda
-- hicbir yerde tanimli degildi. `select * from cron.job;` ile tespit edildi:
--
--   jobid=1  schedule='15 5 * * *' (08:15 TR)  command='SELECT snapshot_musteri_metrik_gecmis();'  active=true
--   jobid=2  schedule='15 5 * * *' (08:15 TR)  command='SELECT snapshot_urun_stok_gecmis();'        active=true
--
-- Fonksiyon tanimi (`select prosrc from pg_proc where proname = ...`):
--
--   create or replace function public.snapshot_musteri_metrik_gecmis()
--   returns integer
--   language plpgsql
--   as $$
--   declare
--     n integer := 0;
--   begin
--     insert into musteri_metrik_gecmis (
--       musteri_kodu, snapshot_tarihi, net_ciro, siparis_sayisi, fatura_sayisi,
--       acik_bakiye, riskli_bakiye, son_teslimat_tarihi, toplam_teslimat_sayisi, risk_durumu
--     )
--     select
--       h.musteri_kodu, current_date, h.belge_net_ciro, h.belge_siparis_sayisi,
--       h.belge_fatura_sayisi, h.yas_toplam, h.yas_riskli_tutar,
--       h.son_teslimat_tarihi, h.toplam_teslimat_sayisi, h.risk_durumu
--     from musteriler_harita h
--     on conflict (musteri_kodu, snapshot_tarihi) do update set
--       net_ciro = excluded.net_ciro,
--       siparis_sayisi = excluded.siparis_sayisi,
--       fatura_sayisi = excluded.fatura_sayisi,
--       acik_bakiye = excluded.acik_bakiye,
--       riskli_bakiye = excluded.riskli_bakiye,
--       son_teslimat_tarihi = excluded.son_teslimat_tarihi,
--       toplam_teslimat_sayisi = excluded.toplam_teslimat_sayisi,
--       risk_durumu = excluded.risk_durumu;
--
--     get diagnostics n = row_count;
--     return n;
--   end;
--   $$;
--
-- `h.belge_net_ciro` musteriler_harita view'indan geliyor — yani
-- sql/net_ciro_kdv_haric.sql'deki KDV-haric duzeltmesi buraya da otomatik
-- yansiyor (fonksiyon degismedi, view'in sagladigi deger degisti).
--
-- HALA YAPILMASI GEREKEN: bu fonksiyon/job Supabase konsolunda tanimli,
-- migration dosyalarinda degil — degistirmek icin SQL Editor veya
-- apply_migration kullanilmali, repo icin sadece belge amacli buraya
-- kopyalandi. `snapshot_urun_stok_gecmis()` de ayni sekilde repo disi.
-- =============================================================================
