-- =============================================================================
-- musteri_metrik_gecmis — gunluk metrik anlik goruntusu (2026-08-11 audit'i, K3)
-- =============================================================================
--
-- NE ISE YARIYOR
--   Raporlama tablosundaki "Trend 14g" sparkline'inin TEK veri kaynagi
--   (frontend/hooks/useMusteriRaporlama.ts -> useMusteriTrend).
--   Her gun her musteri icin bir satir birikiyor.
--
-- !! DIKKAT — BU DOSYA MEVCUT DURUMUN BELGESIDIR, KAYNAGI DEGILDIR !!
--   Audit sirasinda tespit edildi: bu tabloyu YAZAN is repoda YOK.
--   Ne DDL, ne cron, ne Edge Function, ne trigger — hicbir sey. Buna ragmen
--   tablo her gun dolmaya devam ediyor (9/10/11 Agu -> 1200/1200/1203 satir),
--   yani Supabase projesinde surum kontrolu DISINDA bir is calisiyor
--   (buyuk ihtimalle pg_cron job'u veya zamanlanmis bir function).
--
--   Sonuc: bu is gozden gecirilemiyor, degistirilemiyor, bozulursa geri
--   alinamiyor ve kimse fark etmeden durabilir — durursa sparkline sessizce
--   donar (tıpkı 2026-08-06'daki transform olayi gibi).
--
-- YAPILMASI GEREKEN (bu dosya tek basina yeterli DEGIL)
--   1) Supabase'de yazan isi bul:
--        select * from cron.job;                       -- pg_cron kurulu ise
--        select proname, prosrc from pg_proc
--         where prosrc ilike '%musteri_metrik_gecmis%';
--   2) Bulunan job/function tanimini bu dosyanin altina EKLE, boylece kaynak
--      surum kontrolune girsin.
--   3) O zamana kadar: tablonun her gun dolup dolmadigini izle.
--
-- Asagidaki tablo tanimi CANLI SEMADAN turetildi (PostgREST ile gozlemlenen
-- kolonlar ve degerler). Tablo zaten var; bu blok yalnizca yeniden kurulum /
-- ikinci ortam icin idempotent olarak yazildi.
-- =============================================================================

create table if not exists public.musteri_metrik_gecmis (
  id                     bigint generated by default as identity primary key,
  musteri_kodu           text not null,
  snapshot_tarihi        date not null,
  net_ciro               numeric,
  siparis_sayisi         integer,
  fatura_sayisi          integer,
  acik_bakiye            numeric,
  riskli_bakiye          numeric,
  son_teslimat_tarihi    date,
  toplam_teslimat_sayisi integer not null default 0,
  risk_durumu            text,
  unique (musteri_kodu, snapshot_tarihi)
);

-- useMusteriTrend: son 14 gunu musteri_kodu listesiyle cekiyor.
create index if not exists idx_metrik_gecmis_kod_tarih
  on public.musteri_metrik_gecmis (musteri_kodu, snapshot_tarihi desc);

create index if not exists idx_metrik_gecmis_tarih
  on public.musteri_metrik_gecmis (snapshot_tarihi desc);

alter table public.musteri_metrik_gecmis enable row level security;

-- UI anon anahtarla okuyor (RAPORLAMA-SAYFASI.md:215 bu boslugu isaret ediyordu).
drop policy if exists "metrik_gecmis_read" on public.musteri_metrik_gecmis;
create policy "metrik_gecmis_read"
  on public.musteri_metrik_gecmis
  for select
  to anon, authenticated
  using (true);

-- Dogrulama — gunluk is calisiyor mu:
--   select snapshot_tarihi, count(*)
--     from public.musteri_metrik_gecmis
--    group by 1 order by 1 desc limit 14;
-- Beklenen: her gun icin ~musteri sayisi kadar satir, bosluk yok.
