-- =============================================================================
-- 5230 TahsilatRaporu — typed landing + müşteri özeti + guncel view
-- =============================================================================
--
-- Nakit girişi defteri (makbuz/çek/senet), fatura cirosu DEĞİL.
-- Excel kolonları n8n toSnake ile birebir: 29 text kolon + sync_id.
-- PII (tc_kimlik_no, vergi_no) landing'de durur; UI SELECT etmez.
--
-- Uygula: MCP apply_migration / SQL Editor. Idempotent (drop + create).
-- View gövdesi sql/raporlama_view_koordinatsiz.sql ile AYNI tutulmalı.
-- =============================================================================

drop view if exists public.v_panorama_tahsilat_raporu_guncel;

drop table if exists public.panorama_tahsilat_raporu;

create table public.panorama_tahsilat_raporu (
    id                     bigint generated by default as identity primary key,
    sync_id                uuid not null references public.panorama_sync_runs (id) on delete cascade,
    aciklama               text,
    cek_no                 text,
    odeme_durum            text,
    satis_temsilcisi       text,
    tc_kimlik_no           text,
    vergi_no               text,
    tahsilat_tur           text,
    dist                   text,
    musteri_kod            text,
    musteri_unvan          text,
    islem_tarihi           text,
    islem_tip              text,
    ba                     text,
    giris_tipi             text,
    belgekod               text,
    banka                  text,
    belge_no               text,
    makbuz_no              text,
    tahsilat_tipi          text,
    rut_grup_ad            text,
    tahsilat_iptal_neden   text,
    musteri_grup_kodu      text,
    musteri_ek_grup_kod    text,
    musteri_grup_ad        text,
    musteri_ek_grup_ad     text,
    esas_borclu            text,
    sube                   text,
    vade_tarihi            text,
    tutar                  text
);

create index idx_tahsilat_sync_id
  on public.panorama_tahsilat_raporu (sync_id);

create index idx_tahsilat_musteri_kod
  on public.panorama_tahsilat_raporu (musteri_kod);

alter table public.panorama_tahsilat_raporu enable row level security;

do $$ begin
  create policy "panorama_tahsilat_raporu_select_public"
    on public.panorama_tahsilat_raporu
    for select
    to anon, authenticated
    using (true);
exception when duplicate_object then null;
end $$;

grant select, insert, update, delete on public.panorama_tahsilat_raporu
  to anon, authenticated, service_role;

grant usage, select on sequence public.panorama_tahsilat_raporu_id_seq
  to anon, authenticated, service_role;

create view public.v_panorama_tahsilat_raporu_guncel
with (security_invoker = true) as
select *
  from public.panorama_tahsilat_raporu m
 where m.sync_id = (
   select r.id
     from public.panorama_sync_runs r
    where r.durum = 'completed'
      and r.report_id = 5230
    order by r.cekildi_at desc
    limit 1
 );

grant select on public.v_panorama_tahsilat_raporu_guncel to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Müşteri nakit özeti — harita Özet/Borçlar. Transform replace eder.
-- ---------------------------------------------------------------------------

create table if not exists public.musteri_tahsilat_ozet (
    musteri_kodu         text primary key references public.musteriler (musteri_kodu) on delete cascade,
    son_tahsilat_tarihi  date,
    tahsilat_7g          numeric(16,2) not null default 0,
    tahsilat_30g         numeric(16,2) not null default 0,
    tahsilat_ytd         numeric(16,2) not null default 0,
    odenmemis_tutar      numeric(16,2) not null default 0,
    odenmemis_adet       integer not null default 0,
    satir_sayisi         integer not null default 0,
    guncellendi          timestamptz not null default now()
);

alter table public.musteri_tahsilat_ozet enable row level security;

do $$ begin
  create policy "musteri_tahsilat_ozet_select_public"
    on public.musteri_tahsilat_ozet
    for select
    to anon, authenticated
    using (true);
exception when duplicate_object then null;
end $$;

grant select on public.musteri_tahsilat_ozet to anon, authenticated, service_role;

create or replace function public.replace_musteri_tahsilat_ozet(p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  n integer := 0;
begin
  if not pg_try_advisory_xact_lock(hashtext('replace_musteri_tahsilat_ozet')) then
    raise notice 'replace_musteri_tahsilat_ozet: already running, skipping';
    return 0;
  end if;

  if p_rows is not null and jsonb_typeof(p_rows) is distinct from 'array' then
    raise exception 'replace_musteri_tahsilat_ozet: p_rows must be a JSON array';
  end if;

  delete from public.musteri_tahsilat_ozet
  where musteri_kodu is not null;

  if p_rows is null or jsonb_array_length(p_rows) = 0 then
    return 0;
  end if;

  insert into public.musteri_tahsilat_ozet (
    musteri_kodu,
    son_tahsilat_tarihi,
    tahsilat_7g,
    tahsilat_30g,
    tahsilat_ytd,
    odenmemis_tutar,
    odenmemis_adet,
    satir_sayisi,
    guncellendi
  )
  select
    r.musteri_kodu,
    r.son_tahsilat_tarihi,
    coalesce(r.tahsilat_7g, 0),
    coalesce(r.tahsilat_30g, 0),
    coalesce(r.tahsilat_ytd, 0),
    coalesce(r.odenmemis_tutar, 0),
    coalesce(r.odenmemis_adet, 0),
    coalesce(r.satir_sayisi, 0),
    now()
  from jsonb_to_recordset(p_rows) as r(
    musteri_kodu text,
    son_tahsilat_tarihi date,
    tahsilat_7g numeric,
    tahsilat_30g numeric,
    tahsilat_ytd numeric,
    odenmemis_tutar numeric,
    odenmemis_adet integer,
    satir_sayisi integer
  )
  where r.musteri_kodu is not null and btrim(r.musteri_kodu) <> '';

  get diagnostics n = row_count;
  return n;
end;
$function$;

revoke all on function public.replace_musteri_tahsilat_ozet(jsonb) from public, anon, authenticated;
grant execute on function public.replace_musteri_tahsilat_ozet(jsonb) to service_role;

-- Agent: guncel view invoker zinciri + rapor view join.
grant select on public.panorama_tahsilat_raporu to locus_agent_ro;
grant select on public.v_panorama_tahsilat_raporu_guncel to locus_agent_ro;
grant select on public.musteri_tahsilat_ozet to locus_agent_ro;

do $$
declare
  t text;
begin
  foreach t in array array[
    'panorama_tahsilat_raporu',
    'musteri_tahsilat_ozet'
  ]
  loop
    execute format('drop policy if exists agent_ro_select on public.%I', t);
    execute format(
      'create policy agent_ro_select on public.%I for select to locus_agent_ro using (true)',
      t
    );
  end loop;
end
$$;
