-- =============================================================================
-- BelgeDetayRaporu sipariş kanalı — Panorama 5450 HTTP, sync_runs 5451
-- =============================================================================
--
-- Mevcut fatura 5450 (panorama_belge_detay_raporu / BD / BD2) DEĞİŞMEZ.
-- Aynı Panorama raporu (id=5450) sipariş filtresiyle (Edt_R4_C1_186=1) ayrı
-- çekilir. panorama_sync_runs.report_id = 5451 ki fatura transform'u
-- karışmasın.
--
-- Snapshot: her sync yeni satır + sync_id. guncel view = son completed 5451.
-- İptal / faturalaşmış siparişler yeni Excel'de yoksa listeden düşer
-- (5140 snapshot view de son completed'e bakıyor; upsert kalıntısı yok).
--
-- Uygula: MCP apply_migration / SQL Editor. Idempotent (drop + create).
-- =============================================================================

drop view if exists public.v_panorama_siparis_detay_raporu_guncel;

drop table if exists public.panorama_siparis_detay_raporu;

create table public.panorama_siparis_detay_raporu (
    id                     bigint generated by default as identity primary key,
    sync_id                uuid not null references public.panorama_sync_runs (id) on delete cascade,
    depo_ad                text,
    dist_durum             text,
    dist_ad                text,
    dist                   text,
    dist_unvan             text,
    dist_grup              text,
    bekleyen_siparis       text,
    musteri_kisa_ad        text,
    musteri_unvan          text,
    vade_gunu              text,
    islem_tarihi           text,
    olusturma_tarihi       text,
    vade_tarihi            text,
    matbu_no               text,
    fatura_no              text,
    sira                   text,
    siparis_no             text,
    urun                   text,
    irsaliye_no            text,
    birim                  text,
    urun_kodu              text,
    urun_grup              text,
    urun_ek_grup           text,
    iptal_neden            text,
    musteri_kod            text,
    musteri_merkez_kod     text,
    musteri_grup           text,
    musteri_ek_grup        text,
    satis_temsilcisi       text,
    st_kodu                text,
    belge_tip              text,
    durum                  text,
    kayittip               text,
    islem_tip              text,
    basim_durumu           text,
    musteri_takip_kod      text,
    urunhiyerarsi1         text,
    urunhiyerarsi2         text,
    aciklama               text,
    aktarim                text,
    ozel_kod               text,
    ara_toplam             text,
    miktar                 text,
    birim_fiyat            text,
    brut_tutar             text,
    iskonto                text,
    oiv2_tutar             text,
    otv_tutar              text,
    kdv_oran               text,
    kdv                    text,
    nettutar               text,
    iskonto1               text,
    iskonto2               text,
    iskonto3               text,
    iskonto4               text,
    iskonto5               text,
    iskonto6               text,
    iskonto7               text,
    iskonto8               text,
    unified_doc            text
);

create index idx_siparis_detay_sync_id
  on public.panorama_siparis_detay_raporu (sync_id);

create index idx_siparis_detay_musteri_kod
  on public.panorama_siparis_detay_raporu (musteri_kod);

create index idx_siparis_detay_siparis_no
  on public.panorama_siparis_detay_raporu (siparis_no);

create index idx_siparis_detay_bekleyen
  on public.panorama_siparis_detay_raporu (bekleyen_siparis);

alter table public.panorama_siparis_detay_raporu enable row level security;

do $$ begin
  create policy "panorama_siparis_detay_raporu_select_public"
    on public.panorama_siparis_detay_raporu
    for select
    to anon, authenticated
    using (true);
exception when duplicate_object then null;
end $$;

grant select, insert, update, delete on public.panorama_siparis_detay_raporu
  to anon, authenticated, service_role;

grant usage, select on sequence public.panorama_siparis_detay_raporu_id_seq
  to anon, authenticated, service_role;

-- Son completed 5451 snapshot. HTTP hâlâ Panorama 5450.
create view public.v_panorama_siparis_detay_raporu_guncel
with (security_invoker = true) as
select *
  from public.panorama_siparis_detay_raporu m
 where m.sync_id = (
   select r.id
     from public.panorama_sync_runs r
    where r.durum = 'completed'
      and r.report_id = 5451
    order by r.cekildi_at desc
    limit 1
 );

grant select on public.v_panorama_siparis_detay_raporu_guncel
  to anon, authenticated, service_role;

comment on table public.panorama_siparis_detay_raporu is
  'BelgeDetayRaporu sipariş kanalı (Panorama 5450 / Edt_R4=1). sync_runs.report_id=5451. Tam snapshot.';

comment on view public.v_panorama_siparis_detay_raporu_guncel is
  'Son completed 5451. İptal/sevk olan satırlar yeni çekimde yoksa düşer.';

grant select on public.panorama_siparis_detay_raporu to locus_agent_ro;
grant select on public.v_panorama_siparis_detay_raporu_guncel to locus_agent_ro;

do $$ begin
  drop policy if exists agent_ro_select on public.panorama_siparis_detay_raporu;
  create policy agent_ro_select
    on public.panorama_siparis_detay_raporu
    for select
    to locus_agent_ro
    using (true);
end $$;
