-- =============================================================================
-- sevkiyat_planlari — kaydedilen araç planları
-- =============================================================================
--
-- Bu tablo ERP'nin veremediğini zamanla biriktirir: HANGİ YÜK HANGİ ARAÇLA
-- GİTTİ. Panorama'da araç alanları sahte tek değer (bkz. sql/araclar_sema.sql),
-- yani araç bazlı geçmiş yalnızca buradan doğabilir.
--
-- Bir ay veri biriktikten sonra iki şey mümkün olur:
--   1. "planlanan vs. gerçekleşen doluluk" raporu
--   2. araclar.max_kg tahminlerinin gerçek yüklerle kalibrasyonu
--
-- Bağımlılık: public.araclar
-- Uygula: MCP apply_migration / SQL Editor. Idempotent.
-- =============================================================================

create table if not exists public.sevkiyat_planlari (
    id              uuid primary key default gen_random_uuid(),
    plan_tarihi     date not null default current_date,
    arac_kod        text not null references public.araclar (kod),
    durum           text not null default 'taslak'
                    check (durum in ('taslak', 'onaylandi', 'tamamlandi', 'iptal')),
    durak_sayisi    integer not null default 0,
    toplam_kg       numeric(12,2) not null default 0,
    toplam_cuval    numeric(10,2) not null default 0,
    -- Planın kaydedildiği andaki doluluk yüzdeleri (0–100). Araç kapasitesi
    -- sonradan düzeltilse bile planın o günkü hâli korunur.
    kg_doluluk      numeric(6,2),
    cuval_doluluk   numeric(6,2),
    -- Google Routes optimizasyonu yapıldıysa trafikli süre / mesafe
    google_sure_sn  integer,
    google_mesafe_m integer,
    not_metni       text,
    olusturuldu     timestamptz not null default now(),
    guncellendi     timestamptz not null default now()
);

create index if not exists sevkiyat_planlari_tarih_idx
  on public.sevkiyat_planlari (plan_tarihi desc, arac_kod);

create table if not exists public.sevkiyat_plan_duraklari (
    id            bigint generated by default as identity primary key,
    plan_id       uuid not null references public.sevkiyat_planlari (id) on delete cascade,
    sira          integer not null,
    musteri_kodu  text not null,
    -- Yük değerleri plan anında DONDURULUR: sipariş sonradan değişse bile
    -- "o gün bu araca ne yüklendi" sorusunun cevabı bozulmaz.
    kg            numeric(10,2) not null default 0,
    cuval_esdeger numeric(8,2) not null default 0,
    unique (plan_id, sira)
);

create index if not exists sevkiyat_plan_duraklari_musteri_idx
  on public.sevkiyat_plan_duraklari (musteri_kodu);

comment on table public.sevkiyat_planlari is
  'Kaydedilen araç planları — ERP''de olmayan araç/yük geçmişinin tek kaynağı.';
comment on column public.sevkiyat_plan_duraklari.kg is
  'Plan anındaki yük — sipariş sonradan değişse bile dondurulmuş kalır.';

alter table public.sevkiyat_planlari      enable row level security;
alter table public.sevkiyat_plan_duraklari enable row level security;

do $$ begin
  create policy "sevkiyat_planlari_select_public"
    on public.sevkiyat_planlari for select to anon, authenticated using (true);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "sevkiyat_plan_duraklari_select_public"
    on public.sevkiyat_plan_duraklari for select to anon, authenticated using (true);
exception when duplicate_object then null;
end $$;

-- Yazma yalnız service_role üzerinden (/api/rota/plan) — anon yazamaz.
grant select on public.sevkiyat_planlari       to anon, authenticated;
grant select on public.sevkiyat_plan_duraklari to anon, authenticated;
grant select, insert, update, delete on public.sevkiyat_planlari       to service_role;
grant select, insert, update, delete on public.sevkiyat_plan_duraklari to service_role;
grant usage, select on sequence public.sevkiyat_plan_duraklari_id_seq  to service_role;

do $$ begin
  grant select on public.sevkiyat_planlari       to locus_agent_ro;
  grant select on public.sevkiyat_plan_duraklari to locus_agent_ro;
  drop policy if exists agent_ro_select on public.sevkiyat_planlari;
  create policy agent_ro_select
    on public.sevkiyat_planlari for select to locus_agent_ro using (true);
  drop policy if exists agent_ro_select on public.sevkiyat_plan_duraklari;
  create policy agent_ro_select
    on public.sevkiyat_plan_duraklari for select to locus_agent_ro using (true);
exception when undefined_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- Plan özeti — kayıtlı planların araç ve tarih kırılımı
-- ---------------------------------------------------------------------------
drop view if exists public.v_sevkiyat_plan_ozet;

create view public.v_sevkiyat_plan_ozet
with (security_invoker = true) as
select
    p.id,
    p.plan_tarihi,
    p.arac_kod,
    a.ad as arac_ad,
    p.durum,
    p.durak_sayisi,
    p.toplam_kg,
    p.toplam_cuval,
    p.kg_doluluk,
    p.cuval_doluluk,
    p.google_sure_sn,
    p.google_mesafe_m,
    p.olusturuldu
from public.sevkiyat_planlari p
join public.araclar a on a.kod = p.arac_kod;

grant select on public.v_sevkiyat_plan_ozet to anon, authenticated, service_role;

do $$ begin
  grant select on public.v_sevkiyat_plan_ozet to locus_agent_ro;
exception when undefined_object then null;
end $$;
