-- =============================================================================
-- sevkiyat_planlari — kaydedilen araç planları
-- =============================================================================
--
-- Bu tablo ERP'nin veremediğini zamanla biriktirir: HANGİ YÜK HANGİ ARAÇLA
-- GİTTİ. Panorama'da araç alanları sahte tek değer (bkz. sql/araclar_sema.sql),
-- yani araç bazlı geçmiş yalnızca buradan doğabilir.
--
-- Bir ay veri biriktikten sonra üç şey mümkün olur:
--   1. "planlanan vs. gerçekleşen doluluk" raporu
--   2. araclar.max_kg tahminlerinin gerçek yüklerle kalibrasyonu
--   3. şoför bazlı geçmiş — kim hangi turu sürdü, hangi tur ne kadar sürdü
--
-- Bağımlılık: public.araclar, public.soforler
-- Uygula: MCP apply_migration / SQL Editor. Idempotent.
-- =============================================================================

create table if not exists public.sevkiyat_planlari (
    id              uuid primary key default gen_random_uuid(),
    plan_tarihi     date not null default current_date,
    arac_kod        text not null references public.araclar (kod),
    -- Kim sürdü. Kadrodan silinirse kod NULL''a düşer ama `sofor_ad`
    -- dondurulmuş olduğu için geçmiş kaybolmaz.
    sofor_kod       text references public.soforler (kod) on delete set null,
    sofor_ad        text,
    durum           text not null default 'taslak'
                    check (durum in ('taslak', 'onaylandi', 'tamamlandi', 'iptal')),
    durak_sayisi    integer not null default 0,
    toplam_kg       numeric(12,2) not null default 0,
    toplam_cuval    numeric(10,2) not null default 0,
    -- Planın kaydedildiği andaki doluluk yüzdeleri (0–100). Araç kapasitesi
    -- sonradan düzeltilse bile planın o günkü hâli korunur.
    kg_doluluk      numeric(6,2),
    cuval_doluluk   numeric(6,2),
    -- Google Routes optimizasyonu yapıldıysa trafikli süre / mesafe
    google_sure_sn  integer,
    google_mesafe_m integer,
    not_metni       text,
    olusturuldu     timestamptz not null default now(),
    guncellendi     timestamptz not null default now()
);

create index if not exists sevkiyat_planlari_tarih_idx
  on public.sevkiyat_planlari (plan_tarihi desc, arac_kod);

-- Bir şoför aynı gün iki araca binemez: araç günde tek sefer yapıyor (Melih),
-- yani şoför-gün ikilisi benzersiz. Planlayıcının şoför sınırını veritabanı
-- seviyesinde de garanti eder.
create unique index if not exists sevkiyat_planlari_sofor_gun_idx
  on public.sevkiyat_planlari (plan_tarihi, sofor_kod)
  where sofor_kod is not null;

create index if not exists sevkiyat_planlari_sofor_idx
  on public.sevkiyat_planlari (sofor_kod);

create table if not exists public.sevkiyat_plan_duraklari (
    id            bigint generated by default as identity primary key,
    plan_id       uuid not null references public.sevkiyat_planlari (id) on delete cascade,
    sira          integer not null,
    musteri_kodu  text not null,
    -- Yük değerleri plan anında DONDURULUR: sipariş sonradan değişse bile
    -- "o gün bu araca ne yüklendi" sorusunun cevabı bozulmaz.
    kg            numeric(10,2) not null default 0,
    cuval_esdeger numeric(8,2) not null default 0,
    unique (plan_id, sira)
);

create index if not exists sevkiyat_plan_duraklari_musteri_idx
  on public.sevkiyat_plan_duraklari (musteri_kodu);

comment on table public.sevkiyat_planlari is
  'Kaydedilen araç planları — ERP''de olmayan araç/yük geçmişinin tek kaynağı.';
comment on column public.sevkiyat_plan_duraklari.kg is
  'Plan anındaki yük — sipariş sonradan değişse bile dondurulmuş kalır.';
comment on column public.sevkiyat_planlari.sofor_kod is
  'Planı sürecek şoför. Kadrodan silinirse NULL''a düşer — geçmiş sofor_ad''da korunur.';
comment on column public.sevkiyat_planlari.sofor_ad is
  'Plan anındaki şoför adı, DONDURULMUŞ. Şoför silinse bile "kim sürdü" cevabı kaybolmasın.';

alter table public.sevkiyat_planlari      enable row level security;
alter table public.sevkiyat_plan_duraklari enable row level security;

do $$ begin
  create policy "sevkiyat_planlari_select_public"
    on public.sevkiyat_planlari for select to anon, authenticated using (true);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "sevkiyat_plan_duraklari_select_public"
    on public.sevkiyat_plan_duraklari for select to anon, authenticated using (true);
exception when duplicate_object then null;
end $$;

-- Yazma yalnız service_role üzerinden (/api/rota/plan) — anon yazamaz.
grant select on public.sevkiyat_planlari       to anon, authenticated;
grant select on public.sevkiyat_plan_duraklari to anon, authenticated;
grant select, insert, update, delete on public.sevkiyat_planlari       to service_role;
grant select, insert, update, delete on public.sevkiyat_plan_duraklari to service_role;
grant usage, select on sequence public.sevkiyat_plan_duraklari_id_seq  to service_role;

do $$ begin
  grant select on public.sevkiyat_planlari       to locus_agent_ro;
  grant select on public.sevkiyat_plan_duraklari to locus_agent_ro;
  drop policy if exists agent_ro_select on public.sevkiyat_planlari;
  create policy agent_ro_select
    on public.sevkiyat_planlari for select to locus_agent_ro using (true);
  drop policy if exists agent_ro_select on public.sevkiyat_plan_duraklari;
  create policy agent_ro_select
    on public.sevkiyat_plan_duraklari for select to locus_agent_ro using (true);
exception when undefined_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- Plan özeti — kayıtlı planların araç ve tarih kırılımı
-- ---------------------------------------------------------------------------
drop view if exists public.v_sevkiyat_plan_ozet;

create view public.v_sevkiyat_plan_ozet
with (security_invoker = true) as
select
    p.id,
    p.plan_tarihi,
    p.arac_kod,
    a.ad as arac_ad,
    p.sofor_kod,
    -- Dondurulmuş ad esas; yoksa kadrodaki güncel ada düş.
    coalesce(p.sofor_ad, s.ad) as sofor_ad,
    p.durum,
    p.durak_sayisi,
    p.toplam_kg,
    p.toplam_cuval,
    p.kg_doluluk,
    p.cuval_doluluk,
    p.google_sure_sn,
    p.google_mesafe_m,
    p.olusturuldu
from public.sevkiyat_planlari p
join public.araclar a on a.kod = p.arac_kod
left join public.soforler s on s.kod = p.sofor_kod;

grant select on public.v_sevkiyat_plan_ozet to anon, authenticated, service_role;

do $$ begin
  grant select on public.v_sevkiyat_plan_ozet to locus_agent_ro;
exception when undefined_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- Plan durakları + müşteri bilgisi — "Kaydedilenler" sekmesi bunu okur
-- ---------------------------------------------------------------------------
-- `sevkiyat_plan_duraklari` yalnız musteri_kodu tutuyor (yük dondurulmuş);
-- ekranda ad/ilçe/koordinat göstermek için master ile birleştiriliyor.
-- LEFT JOIN: müşteri master'dan düşse bile plan satırı kaybolmasın.
drop view if exists public.v_sevkiyat_plan_duraklari;

create view public.v_sevkiyat_plan_duraklari
with (security_invoker = true) as
select
    d.plan_id,
    d.sira,
    d.musteri_kodu,
    d.kg,
    d.cuval_esdeger,
    r.unvan,
    r.ilce,
    r.sehir,
    r.lat,
    r.lon,
    r.risk_durumu
from public.sevkiyat_plan_duraklari d
left join public.musteriler_rapor r
       on r.musteri_kodu = d.musteri_kodu;

comment on view public.v_sevkiyat_plan_duraklari is
  'Kaydedilmiş plan durakları + müşteri adı/konumu. kg ve çuval plan anındaki DONDURULMUŞ değerler.';

grant select on public.v_sevkiyat_plan_duraklari to anon, authenticated, service_role;

do $$ begin
  grant select on public.v_sevkiyat_plan_duraklari to locus_agent_ro;
exception when undefined_object then null;
end $$;
