-- =============================================================================
-- urun_skt — fabrika alış raporundan ürün SKT / parti kayıtları (2026-08-21)
-- =============================================================================
--
-- KAYNAK
--   Panorama DEĞİL. ARMA İlaç (fabrika) tarafından 15 günde bir hazırlanıp
--   e-posta ile gönderilen "PATİGO FABRİKA ALIŞ TARİH.xlsx" dosyası; uygulama
--   içindeki Veri Yükle akışıyla (dosya tipi: FabrikaSktRaporu) işleniyor.
--   Panorama otomasyon zincirine BAĞLI DEĞİL — otomatik tazelenmiyor.
--
-- GRAIN
--   Bir satır = (alım kalemi × SKT hücresi). Dosyada tek bir alım kalemi
--   5'e kadar parti/SKT taşıyabiliyor (aynı adlı 5 kolon). Hiç SKT hücresi
--   dolu olmayan kalemler de durum='kayit_yok' ile TEK satır olarak yazılır —
--   "kaç alım kaleminde SKT kaydı yok" sorusu ancak böyle cevaplanabiliyor
--   (ekranda "kısmi kapsam" uyarısını bu besliyor).
--
-- MIKTAR UYARISI
--   satir_miktar, alım KALEMİNİN toplam miktarıdır; partiler arasında nasıl
--   bölündüğü dosyada yazmıyor (560 kalemin 93'ü çok partili). Bu yüzden
--   çok partili kalemlerde "bu SKT'den şu kadar adet var" DENEMEZ.
--   tek_parti=true olan kalemlerde miktar güvenilir.
--
-- TAM DEĞİŞTİRME
--   Her yükleme tabloyu tamamen değiştirir (replace_urun_skt RPC).
--   Bilinçli karar: bu bir stok anlık görüntüsü, tarihçe tutulmuyor —
--   en güncel sayım her zaman doğru olan.
-- =============================================================================

create table if not exists public.urun_skt (
  id            bigint generated by default as identity primary key,
  -- Katalogdaki gerçek ürün kodu (v_panorama_detayli_stok_raporu_guncel.urun_kodu).
  -- Dosya ürün ADI taşıyor; kod, yükleme sırasında ad eşleştirmesiyle çözülüyor.
  -- 2026-08-21 ölçümü: 84/84 ürün adı birebir eşleşti.
  urun_kodu     text not null,
  -- Dosyadaki ham ad — eşleştirme sonradan tartışılırsa iz sürmek için.
  urun_adi      text not null,
  matbu_no      text,
  islem_tarihi  date,
  satir_miktar  numeric(14,2),
  parti_no      text,
  skt_tarihi    date,
  -- 'tarihli'    → skt_tarihi dolu
  -- 'cozulemedi' → hücrede kayıt var ama tarih çıkarılamadı (parti kodu, tanınmayan format)
  -- 'devir'      → "ESKİ BAYİ DEVİR"; eski bayi artık mevcut değil, SKT KALICI olarak bilinmiyor
  -- 'kayit_yok'  → hücre boş / "0"
  durum         text not null check (durum in ('tarihli', 'cozulemedi', 'devir', 'kayit_yok')),
  -- Alım kaleminde tek parti mi — satir_miktar'ın bu SKT'ye atfedilebilirliği.
  tek_parti     boolean not null default false,
  yuklendi_at   timestamptz not null default now()
);

create index if not exists urun_skt_kod_idx on public.urun_skt (urun_kodu);
create index if not exists urun_skt_tarih_idx on public.urun_skt (skt_tarihi)
  where skt_tarihi is not null;

alter table public.urun_skt enable row level security;

drop policy if exists "urun_skt_select_public" on public.urun_skt;
create policy "urun_skt_select_public"
  on public.urun_skt
  for select
  to anon, authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- Tam değiştirme RPC — DELETE + INSERT tek transaction'da.
--
-- musteri_yaslandirma / musteri_belge_ozet ile aynı desen, ama o ikisinin RPC
-- tanımı yalnızca canlı DB'de duruyor (bkz. docs/tech-debt.md şema kayması).
-- Bu tanım baştan sürüm kontrolünde — aynı hataya düşmeyelim.
-- ---------------------------------------------------------------------------
create or replace function public.replace_urun_skt(p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  n integer := 0;
begin
  -- WHERE zorunlu: Supabase'de pg_safeupdate açık, koşulsuz DELETE
  -- "DELETE requires a WHERE clause" ile reddediliyor (2026-08-21'de canlıda
  -- alındı). id her satırda dolu (PK) — koşul pratikte tümünü siler.
  delete from public.urun_skt where id is not null;

  insert into public.urun_skt (
    urun_kodu, urun_adi, matbu_no, islem_tarihi,
    satir_miktar, parti_no, skt_tarihi, durum, tek_parti
  )
  select
    r.urun_kodu, r.urun_adi, r.matbu_no, r.islem_tarihi,
    r.satir_miktar, r.parti_no, r.skt_tarihi, r.durum, r.tek_parti
  from jsonb_to_recordset(p_rows) as r(
    urun_kodu    text,
    urun_adi     text,
    matbu_no     text,
    islem_tarihi date,
    satir_miktar numeric,
    parti_no     text,
    skt_tarihi   date,
    durum        text,
    tek_parti    boolean
  );

  get diagnostics n = row_count;
  return n;
end;
$$;

revoke all on function public.replace_urun_skt(jsonb) from public, anon, authenticated;

-- Doğrulama:
--   select durum, count(*) from public.urun_skt group by 1 order by 2 desc;
--   select count(distinct urun_kodu) from public.urun_skt;
--   -- en yakın 10 SKT:
--   select urun_kodu, urun_adi, skt_tarihi, parti_no
--     from public.urun_skt where skt_tarihi is not null
--    order by skt_tarihi limit 10;
